DATA:
  IMG_SIZE: 224
  DATASET: elegans
MODEL:
  TYPE: swin
  NAME: elegans_count
  DROP_PATH_RATE: 0.5
  DROP_RATE: 0.5
  NUM_CLASSES: 1
  TASK_TYPE: reg
  PROJECT_NAME: elegans_count
  RUN_ID: elegans
  LABEL_SMOOTHING: 0.0
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-4 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0