DATA:
  IMG_SIZE: 512
  DATASET: fetal
  BATCH_SIZE: 8
MODEL:
  TYPE: swin
  NAME: fetal_large_cls
  DROP_PATH_RATE: 0.5
  DROP_RATE: 0.3
  NUM_CLASSES: 7
  TASK_TYPE: cls
  PROJECT_NAME: fetal_large_cls2
  RUN_ID: fetal_cls2
  AFFIX: _cls.csv
  LABEL_SMOOTHING: 0.0
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 16
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-3 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0