DATA:
  IMG_SIZE: 224
  DATASET: fetal
  BATCH_SIZE: 32
MODEL:
  TYPE: swin
  NAME: fetal_tiny_cls_head
  DROP_PATH_RATE: 0.3
  DROP_RATE: 0.4
  NUM_CLASSES: 3
  TASK_TYPE: cls
  PROJECT_NAME: fetal_tiny_head
  RUN_ID: fetal_reg_head
  AFFIX: _cls1_ng.csv
  LABEL_SMOOTHING: 0.0
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1.25e-3 # 4096 batch-size
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
AUG:
  MIXUP: 0.0
  CUTMIX: 0.0